services:
  blazorapp:
    image: ${DOCKER_REGISTRY-}blazorapp
    build:
      context: .
      dockerfile: BlazorApp/Dockerfile
  authconnector:
    image: ${DOCKER_REGISTRY-}authconnector
    build:
      context: .
      dockerfile: AuthConnector/Dockerfile